services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 